# Use root/example as user/password credentials
version: "3.1"

services:

  # frontend:
  #   container_name: web-app-frontend
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - '80:3000'

  # backend:
  #   container_name: web-app-backend
  #   restart: always
  #   build: ./backend
  #   ports:
  #     - '8011:8011'
  #   depends_on:
  #     - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres